/*
*代码由 TinyRPC 自动生成，请勿修改
*don't modify manually as it generated by TinyRPC
*/
using System;
using zFramework.TinyRPC.Messages;
namespace zFramework.TinyRPC.Generated
{
    /// <summary>
    ///  Test for Handler Regist by Attribute
    /// </summary>
    [Serializable]
    public partial class AttributeRegistTestMessage : Message
    {
        public string desc;
        public override void OnRecycle()
        {
            base.OnRecycle();
            desc = "";
        }
    }
}
