/*
*代码由 TinyRPC 自动生成，请勿修改
*don't modify manually as it generated by TinyRPC
*/
using System;
using zFramework.TinyRPC.Messages;
namespace zFramework.TinyRPC.Generated
{
    [Serializable]
    public partial class G2C_Test : Message
    {
        public UnitInfo UnitInfo;
        public override void OnRecycle()
        {
            base.OnRecycle();
            UnitInfo = default;
        }
    }
}
