/*
*代码由 TinyRPC 自动生成，请勿修改
*don't modify manually as it generated by TinyRPC
*/
using System;
using UnityEngine;
using zFramework.TinyRPC.Messages;
namespace zFramework.TinyRPC.Generated
{
    /// <summary>
    ///  C2S = Client to Server
    /// </summary>
    [Serializable]
    [ResponseType(typeof(S2C_Login))]
    public partial class C2S_Login : Request
    {
        public string name;
        public string password;
        public Vector3 position;
        public Quaternion rotation;
        public Vector2 moveDirection;
        public Vector4 test;
        public Color color;
        public Color32 color32;
        public LayerMask layerMask;
        public Matrix4x4 matrix;
        public Rect rect;
        public override void OnRecycle()
        {
            base.OnRecycle();
            name = "";
            password = "";
            position = default;
            rotation = default;
            moveDirection = default;
            test = default;
            color = default;
            color32 = default;
            layerMask = default;
            matrix = default;
            rect = default;
        }
    }
}
