/*
*代码由 TinyRPC 自动生成，请勿修改
*don't modify manually as it generated by TinyRPC
*/
using System;
using zFramework.TinyRPC.Messages;
namespace zFramework.TinyRPC.Generated
{
    /// <summary>
    ///  C2S = Client to Server
    /// </summary>
    [Serializable]
    [ResponseType(typeof(S2C_Login))]
    public partial class C2S_Login : Request
    {
        public string name;
        public string password;
        public override void OnRecycle()
        {
            base.OnRecycle();
            name = "";
            password = "";
        }
    }
}
