/*
*代码由 TinyRPC 自动生成，请勿修改
*don't modify manually as it generated by TinyRPC
*/
using System;
using System.Collections.Generic;
using zFramework.TinyRPC.Messages;
namespace zFramework.TinyRPC.Generated
{
    [Serializable]
    public partial class M2C_Reload : Response
    {
        public string Message;
        public List<MoveInfo> moveInfo = new();
        public override void OnRecycle()
        {
            base.OnRecycle();
            Message = "";
            moveInfo = null;
        }
    }
}
