/*
*代码由 TinyRPC 自动生成，请勿修改
*don't modify manually as it generated by TinyRPC
*/
using System;
using zFramework.TinyRPC.Messages;
namespace zFramework.TinyRPC.Generated
{
    /// <summary>
    ///  注释bb
    ///  xxxx muilt summary
    /// </summary>
    [Serializable]
    public partial class TestRPCResponse : Response
    {
        public string name;
        public override void OnRecycle()
        {
            base.OnRecycle();
            name = "";
        }
    }
}
