/*
*代码由 TinyRPC 自动生成，请勿修改
*don't modify manually as it generated by TinyRPC
*/
using System;
using zFramework.TinyRPC.Messages;
namespace zFramework.TinyRPC.Generated
{
    /// <summary>
    ///  注释aa
    /// </summary>
    [Serializable]
    [ResponseType(typeof(TestRPCResponse))]
    public partial class TestRPCRequest : Request
    {
        public string name;
        public override void OnRecycle()
        {
            base.OnRecycle();
            name = "";
        }
    }
}
