/*
*代码由 TinyRPC 自动生成，请勿修改
*don't modify manually as it generated by TinyRPC
*/
using System;
using System.Collections.Generic;
namespace zFramework.TinyRPC.Generated
{
    /// <summary>
    ///  角色移动信息
    /// </summary>
    public struct MoveInfo
    {
        public List<float> X;
        public List<float> Y;
        public List<float> Z;
        public float A;
        public float B;
        public float C;
        public float W;
        public int TurnSpeed;
    }
}
