/*
*代码由 TinyRPC 自动生成，请勿修改
*don't modify manually as it generated by TinyRPC
*/
using System;
using System.Collections.Generic;
namespace zFramework.TinyRPC.Generated
{
    /// <summary>
    ///  角色移动信息
    /// </summary>
    [Serializable]
    public partial class MoveInfo
    {
        public List<float> X = new();
        public List<float> Y = new();
        public List<float> Z = new();
        public float A;
        /// <summary>
        ///  it is B
        /// </summary>
        public float B;
        public float C;
        public float W;
        public int TurnSpeed;
    }
}
