/*
*代码由 TinyRPC 自动生成，请勿修改
*don't modify manually as it generated by TinyRPC
*/
using System;
using System.Collections.Generic;
namespace zFramework.TinyRPC.Generated
{
    public struct UnitInfo
    {
        public long UnitId;
        public int ConfigId;
        public int Type;
        public float X;
        public float Y;
        public float Z;
        public float ForwardX;
        public float ForwardY;
        public float ForwardZ;
        public List<int> Ks;
        public List<long> Vs;
        public MoveInfo MoveInfo;
    }
}
